# Generated by Django 2.0.5 on 2018-05-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateField(auto_now_add=True, verbose_name='Date create message')),
                ('data_last_chenges', models.DateField(auto_now=True, verbose_name='Date chenges message')),
                ('text_message', models.TextField(help_text='message max length 512 chars', max_length=512, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=128, unique=True, verbose_name='User role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='User first name')),
                ('last_name', models.CharField(max_length=128, verbose_name='User last name')),
                ('email', models.EmailField(help_text='Unique email', max_length=254, unique=True, verbose_name='User email')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messages_app.Role')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messages_app.User'),
        ),
    ]
