# Generated by Django 2.0.5 on 2018-05-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_auto_20180528_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.AlterField(
            model_name='message',
            name='data_create',
            field=models.DateField(auto_now_add=True, verbose_name='date create'),
        ),
        migrations.AlterField(
            model_name='message',
            name='data_last_chenges',
            field=models.DateField(auto_now=True, verbose_name='date chenges'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_message',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
