# Generated by Django 2.0.5 on 2018-06-23 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_historicalmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmessage',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='history_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
